- name: Deploy Docker Compose project
  hosts: local
  vars:
    compose_project_dir: "./"
    compose_file: "docker-compose.yml"
    compose_project_name: "test_compose"
  tasks:
   - name: Test
      command: cat 987213
   - name: Build and start Docker Compose project
      command: >
        docker-compose -f {{ compose_project_dir }}/{{ compose_file }} -p {{ compose_project_name }} up -d --build
      args:
        chdir: "{{ compose_project_dir }}"
