# name: Docker Image CI

 on:
   push:
     branches: [ "master" ]
   pull_request:
     branches: [ "master" ]
 jobs:
   run-playbooks:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Code
         uses: actions/checkout@v2
         
       - name: Setup SSH keys
         uses: webfactory/ssh-agent@v0.4.1
         with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY }}

       - name: Clone repository on remote host
         run: |
              ssh-keyscan -t rsa ${{ secrets.IP_ADDRESS }} >> ~/.ssh/known_hosts
              git remote add deploy ${{ secrets.USERNAME }}@${{ secrets.IP_ADDRESS }}:/home/mdev/server_git.git
              git push deploy master
         env:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
